# Generated by Django 6.0.6 on 2026-06-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(blank=True, to='students.tag'),
        ),
    ]
