# Generated by Django 6.0.6 on 2026-07-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('can_promote_student', 'Can promote student'), ('can_expel_student', 'Can expel student')], 'verbose_name': 'студент', 'verbose_name_plural': 'студенты'},
        ),
    ]
